### ISSUE TITLE
Query By Example vs. VC Data Model

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vp-request-spec#10]
The [Query By Example query example](https://w3c-ccg.github.io/vp-request-spec/#example-2-a-query-by-example-query) contains two properties in the `example` credential that are not in the [VC Data Model](https://w3c.github.io/vc-data-model/) or in the JSON-LD contexts of the credential:
- `trustedIssuer`
- `issuerQuery`

Should these two properties be moved up a level or two so to be out of the example credential object?

In general, should the credential in the `QueryByExample` `credentialQuery` `example` object be valid according to `vc-data-model` and/or `vc-test-suite`? (e.g. must have a `issuer` URI, `issuanceDate`, and `credentialSubject`.) Or is it its own thing that looks like a credential but has these additional properties that we could define? If it is strictly according to `vc-data-model`, how can it represent allowing one of multiple issuers?

Could an existing standard be used here instead? e.g. [JSON Schema](https://json-schema.org/). There is also [JSON Predicates](https://tools.ietf.org/html/draft-snell-json-test-07) but that is expired. Or is better to have a custom predicate format for credentials?

**Comment by dlongley** [comment]
Ah, this is a mistake in the indentation and a similar issue was raised about it in #29. PR #30 will address it. The properties should not appear within the `example` (where VCDM properties would be used), but in the `QueryByExample` main body.

**Comment by dlongley** [comment]
This has now been addressed by #30.
