### ISSUE TITLE
DID Authentication vs. VC Test Suite

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vp-request-spec#11]
The [example DID Authentication response](https://w3c-ccg.github.io/vp-request-spec/#example-4-a-didauth-response) is currently invalid according to [vc-test-suite](https://github.com/w3c/vc-test-suite/), because of not containing a verifiable credential, although this is valid in [vc-data-model](https://github.com/w3c/vc-data-model). Issue on vc-test-suite about this: https://github.com/w3c/vc-test-suite/issues/112; proposed fix: https://github.com/w3c/vc-test-suite/pull/113

**Comment by msporny** [comment]
The group discussed this on the 2024-07-30 telecon:

The group confirmed that the VC Data Model allows the type of response that is in the VP Request spec for a DID Authentication request (a VC is NOT required in the object). 

The group agreed that this issue can be closed now that the text for DID Authentication has been updated in the VPR spec.
