### ISSUE TITLE
Add EDU "use case" examples for presentation exchange data model

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vp-request-spec#14]
As requested here: https://github.com/w3c-ccg/vp-request-spec/pull/12#discussion_r780856145

"traceability examples are too complicated"... 

I don't agree with this comment, but I think they might not be the "best example" to lead with.

This issue is to request a simpler use case to start with.

**Comment by msporny** [comment]
The group discussed this on the 2024-07-30 telecon:

The group felt like there will be other opportunities to add examples into the specification and didn't feel like an EDU use case was necessary at this point in time. @msporny confirmed that he no longer requires an EDU use case in the specification and other examples will be added as other issues are processed. 

The group agreed to close this issue and wait for more specific example needs as needed in future PRs.
